# Generated by Django 4.2.9 on 2026-06-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('receptionist', 'Receptionist'), ('clinician', 'Clinician'), ('technician', 'Lab Technician'), ('pharmacist', 'Pharmacist'), ('accountant', 'Accountant'), ('manager', 'Lab Manager'), ('scientist', 'Lab Scientist')], default='receptionist', max_length=20),
        ),
    ]
