# Generated by Django 4.2.9 on 2026-03-19 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('catalog_number', models.CharField(max_length=50, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('unit', models.CharField(choices=[('ml', 'mL'), ('l', 'L'), ('mg', 'mg'), ('g', 'g'), ('units', 'Units'), ('tests', 'Tests'), ('vials', 'Vials'), ('kits', 'Kits')], default='units', max_length=20)),
                ('stock_quantity', models.FloatField(default=0)),
                ('reorder_level', models.FloatField(default=10)),
                ('max_stock', models.FloatField(default=100)),
                ('storage_condition', models.CharField(blank=True, help_text='e.g. 2–8°C, Room temp', max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, help_text='Fridge/shelf location', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReagentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('receive', 'Received'), ('consume', 'Consumed'), ('adjust', 'Adjustment'), ('dispose', 'Disposed')], max_length=20)),
                ('quantity', models.FloatField()),
                ('quantity_before', models.FloatField()),
                ('quantity_after', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.reagent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reagent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.reagentcategory'),
        ),
    ]
