# Generated by Django 4.2.9 on 2026-03-19 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('sample_type', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('swab', 'Swab'), ('tissue', 'Tissue'), ('csf', 'CSF'), ('stool', 'Stool'), ('sputum', 'Sputum'), ('other', 'Other')], max_length=20)),
                ('priority', models.CharField(choices=[('stat', 'STAT'), ('routine', 'Routine'), ('asap', 'ASAP')], default='routine', max_length=10)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('complete', 'Complete'), ('rejected', 'Rejected'), ('hold', 'On Hold')], default='received', max_length=20)),
                ('collection_site', models.CharField(blank=True, max_length=200)),
                ('collected_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.CharField(blank=True, max_length=100)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('barcode', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='samples.patient')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_samples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
