# Generated by Django 4.2.9 on 2026-03-19 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sla_hours', models.FloatField(default=4.0, help_text='Turnaround time target in hours')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('ref_range_low', models.FloatField(blank=True, null=True)),
                ('ref_range_high', models.FloatField(blank=True, null=True)),
                ('critical_low', models.FloatField(blank=True, null=True)),
                ('critical_high', models.FloatField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='tests.testpanel')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('review', 'Awaiting Review'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('critical_notified', models.BooleanField(default=False)),
                ('critical_notified_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tests', to=settings.AUTH_USER_MODEL)),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_tests', to=settings.AUTH_USER_MODEL)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.testpanel')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_orders', to='samples.sample')),
            ],
            options={
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('flag', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('low', 'Low'), ('critical_high', 'Critical High'), ('critical_low', 'Critical Low')], default='normal', max_length=20)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_results', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tests.testorder')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.testparameter')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['parameter__order'],
                'unique_together': {('order', 'parameter')},
            },
        ),
    ]
