# Generated by Django 4.2.9 on 2026-06-19 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_visit_prescription_at_visit_requires_lab_and_more'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testorder',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_orders', to='visits.visit'),
        ),
    ]
