# Generated by Django 4.2.9 on 2026-03-19 12:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispense_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dispensed_at'],
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup / Liquid'), ('injection', 'Injection'), ('cream', 'Cream / Ointment'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('patch', 'Patch'), ('suppository', 'Suppository'), ('other', 'Other')], default='tablet', max_length=20)),
                ('strength', models.CharField(blank=True, help_text='e.g. 500mg, 250mg/5mL', max_length=50)),
                ('unit', models.CharField(choices=[('tablet', 'Tablet(s)'), ('capsule', 'Capsule(s)'), ('ml', 'mL'), ('mg', 'mg'), ('g', 'g'), ('vial', 'Vial(s)'), ('ampoule', 'Ampoule(s)'), ('tube', 'Tube(s)'), ('bottle', 'Bottle(s)'), ('sachet', 'Sachet(s)'), ('unit', 'Unit(s)')], default='tablet', max_length=20)),
                ('stock_quantity', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_level', models.FloatField(default=50, help_text='Alert when stock falls below this')),
                ('max_stock', models.FloatField(default=500)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('storage_condition', models.CharField(blank=True, help_text='e.g. Below 25°C, Refrigerate', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Shelf / bin location', max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('controlled', models.BooleanField(default=False, help_text='Controlled / narcotic substance')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DrugCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rx_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('partial', 'Partially Dispensed'), ('dispensed', 'Fully Dispensed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('diagnosis', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='samples.patient')),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-prescribed_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(help_text='e.g. 500mg, 2 tablets', max_length=100)),
                ('frequency', models.CharField(help_text='e.g. Twice daily, Every 8 hours', max_length=100)),
                ('duration', models.CharField(help_text='e.g. 7 days, 2 weeks', max_length=100)),
                ('quantity', models.FloatField(help_text='Total quantity to dispense')),
                ('dispensed_qty', models.FloatField(default=0)),
                ('instructions', models.TextField(blank=True, help_text='e.g. Take after meals')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='pharmacy.drug')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.prescription')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DrugStockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('receive', 'Stock Received'), ('dispense', 'Dispensed'), ('adjust', 'Adjustment'), ('return', 'Returned'), ('expire', 'Expired / Disposed')], max_length=20)),
                ('quantity', models.FloatField()),
                ('quantity_before', models.FloatField()),
                ('quantity_after', models.FloatField()),
                ('reference', models.CharField(blank=True, help_text='Dispense ID, batch, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='pharmacy.drug')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='drug',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.drugcategory'),
        ),
        migrations.CreateModel(
            name='DispenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dispensed', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('dispense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.dispense')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.drug')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispense_items', to='pharmacy.prescriptionitem')),
            ],
        ),
        migrations.AddField(
            model_name='dispense',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='pharmacy.prescription'),
        ),
    ]
