# Generated by Django 4.2.9 on 2026-03-19 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('triage', 'Triage / Vitals'), ('consultation', 'Doctor Consultation'), ('lab', 'Sent to Lab'), ('results_ready', 'Lab Results Ready'), ('prescription', 'Prescription Written'), ('pharmacy', 'At Pharmacy'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='registered', max_length=20)),
                ('chief_complaint', models.TextField(blank=True, help_text='Reason for visit')),
                ('notes', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('triage_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_at', models.DateTimeField(blank=True, null=True)),
                ('lab_at', models.DateTimeField(blank=True, null=True)),
                ('pharmacy_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attending_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_visits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='samples.patient')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(blank=True, help_text='e.g. 120/80', max_length=20)),
                ('pulse', models.PositiveIntegerField(blank=True, help_text='bpm', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='°C', null=True)),
                ('weight', models.FloatField(blank=True, help_text='kg', null=True)),
                ('height', models.FloatField(blank=True, help_text='cm', null=True)),
                ('spo2', models.FloatField(blank=True, help_text='% oxygen saturation', null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, help_text='breaths/min', null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vitals', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='visits.visit')),
            ],
        ),
        migrations.CreateModel(
            name='VisitBillingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('registration', 'Registration'), ('consultation', 'Consultation'), ('lab', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_events', to='visits.visit')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenting_complaint', models.TextField(blank=True)),
                ('examination_notes', models.TextField(blank=True)),
                ('diagnosis', models.TextField()),
                ('icd_code', models.CharField(blank=True, help_text='ICD-10 code', max_length=20)),
                ('management_plan', models.TextField(blank=True)),
                ('follow_up', models.TextField(blank=True)),
                ('send_to_lab', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='visits.visit')),
            ],
        ),
    ]
