# Generated by Django 4.2.9 on 2026-06-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='prescription_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='requires_lab',
            field=models.BooleanField(default=True, help_text='Whether lab tests are expected for this visit'),
        ),
        migrations.AddField(
            model_name='visit',
            name='results_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
